# Generated by Django 4.0.3 on 2022-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_contact_email_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_name', models.CharField(max_length=120)),
                ('App_category', models.CharField(max_length=50)),
                ('App_size', models.IntegerField()),
                ('App_info', models.CharField(max_length=500)),
                ('App_pub_date', models.DateField()),
                ('App_image', models.ImageField(upload_to='Store/images')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
    ]
