# Generated by Django 4.0.3 on 2022-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_webstore_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstore',
            name='App_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
